cp plotcard2017_zee_withScaleSmear_cat0EBEB.json plotcard2017_zee_withScaleSmear_with_nonLinearity_cat0EBEB.json
cp plotcard2017_zee_withScaleSmear_cat2EBEB.json plotcard2017_zee_withScaleSmear_with_nonLinearity_cat2EBEB.json
cp plotcard2017_zee_withScaleSmear_cat3EBEB.json plotcard2017_zee_withScaleSmear_with_nonLinearity_cat3EBEB.json