#/bin/bash

# input variables validation
# ./heppi-draw -p plotcardUL16_postVFP.json -o "/eos/user/z/zhenxuan/Hgg_mass/MiniTree/UL2016/postVFP/" -s "/eos/user/z/zhenxuan/Hgg_mass/MiniTree/UL2016/postVFP/" -t {sampleid}_13TeV_UntaggedTag --label zee -v Tran_DiphotonMVA_self
# ./heppi-draw -p plotcardUL16_postVFP.json -o "/eos/cms/store/group/phys_higgs/cmshgg/zhenxuan/Hgg_mass/MiniTree/UL2016/UL16_postVFP" -s "/eos/user/z/zhenxuan/Hgg_mass/MiniTree/UL2016/postVFP/" -t {sampleid}_13TeV_UntaggedTag --label zee -v pt
# ./heppi-draw -p plotcardUL16_postVFP.json -o "/eos/cms/store/group/phys_higgs/cmshgg/zhenxuan/Hgg_mass/MiniTree/UL2016/UL16_postVFP" -s "/eos/user/z/zhenxuan/Hgg_mass/MiniTree/UL2016/postVFP/" -t {sampleid}_13TeV_UntaggedTag --label zee -v CosPhi
# ./heppi-draw -p plotcardUL16_postVFP.json -o "/eos/cms/store/group/phys_higgs/cmshgg/zhenxuan/Hgg_mass/MiniTree/UL2016/UL16_postVFP" -s "/eos/user/z/zhenxuan/Hgg_mass/MiniTree/UL2016/postVFP/" -t {sampleid}_13TeV_UntaggedTag --label zee -v vtxprob
# ./heppi-draw -p plotcardUL16_postVFP.json -o "/eos/cms/store/group/phys_higgs/cmshgg/zhenxuan/Hgg_mass/MiniTree/UL2016/UL16_postVFP" -s "/eos/user/z/zhenxuan/Hgg_mass/MiniTree/UL2016/postVFP/" -t {sampleid}_13TeV_UntaggedTag --label zee -v DiphotonMVA_self
# ./heppi-draw -p plotcardUL16_postVFP.json -o "/eos/cms/store/group/phys_higgs/cmshgg/zhenxuan/Hgg_mass/MiniTree/UL2016/UL16_postVFP" -s "/eos/user/z/zhenxuan/Hgg_mass/MiniTree/UL2016/postVFP/" -t {sampleid}_13TeV_UntaggedTag --label zee -v leadeta
# ./heppi-draw -p plotcardUL16_postVFP.json -o "/eos/cms/store/group/phys_higgs/cmshgg/zhenxuan/Hgg_mass/MiniTree/UL2016/UL16_postVFP" -s "/eos/user/z/zhenxuan/Hgg_mass/MiniTree/UL2016/postVFP/" -t {sampleid}_13TeV_UntaggedTag --label zee -v subleadeta
# ./heppi-draw -p plotcardUL16_postVFP.json -o "/eos/cms/store/group/phys_higgs/cmshgg/zhenxuan/Hgg_mass/MiniTree/UL2016/UL16_postVFP" -s "/eos/user/z/zhenxuan/Hgg_mass/MiniTree/UL2016/postVFP/" -t {sampleid}_13TeV_UntaggedTag --label zee -v leadptom
# ./heppi-draw -p plotcardUL16_postVFP.json -o "/eos/cms/store/group/phys_higgs/cmshgg/zhenxuan/Hgg_mass/MiniTree/UL2016/UL16_postVFP" -s "/eos/user/z/zhenxuan/Hgg_mass/MiniTree/UL2016/postVFP/" -t {sampleid}_13TeV_UntaggedTag --label zee -v subleadptom
# ./heppi-draw -p plotcardUL16_postVFP.json -o "/eos/cms/store/group/phys_higgs/cmshgg/zhenxuan/Hgg_mass/MiniTree/UL2016/UL16_postVFP" -s "/eos/user/z/zhenxuan/Hgg_mass/MiniTree/UL2016/postVFP/" -t {sampleid}_13TeV_UntaggedTag --label zee -v sigmarv
# ./heppi-draw -p plotcardUL16_postVFP.json -o "/eos/cms/store/group/phys_higgs/cmshgg/zhenxuan/Hgg_mass/MiniTree/UL2016/UL16_postVFP" -s "/eos/user/z/zhenxuan/Hgg_mass/MiniTree/UL2016/postVFP/" -t {sampleid}_13TeV_UntaggedTag --label zee -v sigmawv
# ./heppi-draw -p plotcardUL16_postVFP.json -o "/eos/cms/store/group/phys_higgs/cmshgg/zhenxuan/Hgg_mass/MiniTree/UL2016/UL16_postVFP" -s "/eos/user/z/zhenxuan/Hgg_mass/MiniTree/UL2016/postVFP/" -t {sampleid}_13TeV_UntaggedTag --label zee -v leadmva
# ./heppi-draw -p plotcardUL16_postVFP.json -o "/eos/cms/store/group/phys_higgs/cmshgg/zhenxuan/Hgg_mass/MiniTree/UL2016/UL16_postVFP" -s "/eos/user/z/zhenxuan/Hgg_mass/MiniTree/UL2016/postVFP/" -t {sampleid}_13TeV_UntaggedTag --label zee -v subleadmva
./heppi-draw -p plotcardUL16_postVFP.json -o "/eos/cms/store/group/phys_higgs/cmshgg/zhenxuan/Hgg_mass/MiniTree/UL2016/postVFP" -s "/eos/cms/store/group/phys_higgs/cmshgg/zhenxuan/Hgg_mass/MiniTree/UL2016/postVFP" -t {sampleid}_13TeV_UntaggedTag --label zee -v CMS_hgg_mass 