#/bin/bash

WorkDir="/eos/user/z/zhenxuan/wwyy/root_files/boosted_cat/"
OutputDir="/eos/user/z/zhenxuan/wwyy/Plots_wwgg/"
JsonFile="wwgg/wwgg_bkgs_cat1.json"


#mkdir -p plots/${WorkDir}
mkdir -p ${WorkDir}

# input variables validation
./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label wwgg_bkgs -v Diphoton_mass
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_H_Hqqqq_qqlv_vsQCDTop
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label wwgg_bkgs -v Diphoton_minID
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label wwgg_bkgs -v Diphoton_maxID
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_H_pt
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_H_eta
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_H_phi
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_H_mass
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v SubleadPhoton_mvaID
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v LeadPhoton_mvaID
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v Diphoton_eta
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v Diphoton_pt
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label wwgg_bkgs -v maxphotonID
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v Diphoton_eta 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v PuppiMET_phiJERUp 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_3_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v MET_fiducialGenPt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v SubleadPhoton_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_6_btagCMVA 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_4_btagDeepFlavB 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_3_rawFactor 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_4_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_5_btagCSVV2 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_2_qgl 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v SubleadPhoton_mvaID 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_H_Hqqqq_qqlv_vsQCDTop 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_6_btagCSVV2 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v LeadPhoton_mass 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v muon_tightId 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_3_puIdDisc 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_6_genJetIdx 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_2_eta 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v MET_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_4_btagDeepB 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_4_qgl 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v SubleadPhoton_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v PuppiMET_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_H_eta 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_7_btagDeepB 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v LeadPhoton_pixelSeed 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v muon_mass 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_7_btagCMVA 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v GenHggHiggs_eta 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_7_puIdDisc 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_5_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_1_qgl 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_6_btagDeepFlavB 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v GenHggSubleadPhoton_eta 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_7_jetId 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v electron_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v GenHggSubleadPhoton_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v ChsMET_sumEt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_3_mass 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_7_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_3_qgl 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v muon_dz 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v MET_covXX 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v MET_covXY 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v LeadPhoton_mvaID 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_6_puId 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v SubleadPhoton_pixelSeed 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_1_puId 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_1_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v Diphoton_mass 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v GenHggSubleadPhoton_mass 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_6_jetId 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_3_btagCSVV2 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v muon_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v event 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_1_mass 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_1_eta 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v category 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v Diphoton_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_6_mass 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_6_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_H_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v MET_significance 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_1_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v SubleadPhoton_eta 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_1_msoftdrop 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_6_eta 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v GenHggSubleadPhoton_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_5_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v PuppiMET_sumEt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_H_inclParTMDV1_HWWlvqqvsQCDTop 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v LeadPhoton_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_4_mass 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v MET_covYY 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v electron_mvaFall17V2noIso_WP90 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_H_mass 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_7_eta 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_1_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v muon_eta 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_1_btagCSVV2 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v weight_central_initial 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_H_msoftdrop 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v Diphoton_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_1_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_4_btagCSVV2 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_6_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_4_puId 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_2_eta 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_2_btagCMVA 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v GenHggLeadPhoton_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_3_genJetIdx 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_2_btagDeepB 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_4_eta 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_5_eta 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_5_mass 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_7_btagCSVV2 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_7_puId 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_4_btagCMVA 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v GenHggHiggs_mass 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_5_genJetIdx 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v MET_fiducialGenPhi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_H_inclParTMDV1_HWW4q3qvsQCD 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v LeadPhoton_eta 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_1_eta 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_7_btagDeepFlavB 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_1_rawFactor 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_4_rawFactor 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v electron_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_2_mass 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_7_mass 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v electron_dxy 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v weight_central 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_3_btagDeepFlavB 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_3_btagDeepB 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_5_rawFactor 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_2_msoftdrop 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_5_btagDeepB 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v GenHggLeadPhoton_mass 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v PuppiMET_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v weight_central_no_lumi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_6_qgl 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_4_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_2_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_6_btagDeepB 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_4_puIdDisc 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v electron_dz 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_5_puIdDisc 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_7_genJetIdx 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_2_mass 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_3_eta 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_6_rawFactor 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_1_mass 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_1_btagDeepFlavB 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_5_jetId 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_1_genJetIdx 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v electron_mass 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v MET_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_7_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_1_puIdDisc 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_2_genJetIdx 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_3_mass 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v GenHggHiggs_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v ChsMET_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_5_qgl 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v GenHggLeadPhoton_eta 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_H_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_3_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_5_puId 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_1_btagDeepB 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v muon_pfRelIso03_all 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v SubleadPhoton_genPartFlav 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_2_jetId 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_2_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v MET_MetUnclustEnUpDeltaY 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v MET_MetUnclustEnUpDeltaX 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_5_btagDeepFlavB 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_2_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v ChsMET_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_2_puIdDisc 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v electron_eta 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_3_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v muon_dxy 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v Diphoton_dR 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_1_jetId 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v muon_charge 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_6_puIdDisc 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v LeadPhoton_genPartFlav 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v PuppiMET_phiJESUp 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v LeadPhoton_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v MET_sumEt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_1_btagCMVA 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v electron_charge 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v muon_isGlobal 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_3_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v GenHggHiggs_dR 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_2_puId 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v electron_pfRelIso03_all 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v MET_sumPtUnclustered 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v electron_mvaFall17V2Iso_WP90 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v SubleadPhoton_mass 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_2_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v muon_pt 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_2_btagCSVV2 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_2_btagDeepFlavB 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_5_btagCMVA 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v nGoodAK4jets 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_3_eta 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_2_rawFactor 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_4_genJetIdx 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v muon_mediumId 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_3_puId 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_3_jetId 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_3_btagCMVA 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_4_jetId 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_7_rawFactor 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v GenHggHiggs_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v jet_7_qgl 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v GenHggLeadPhoton_phi 
# ./heppi-draw -p $JsonFile -o "/eos/user/z/zhenxuan/wwyy/Plots_wwgg/" -s $WorkDir -t cat1 --label cat1 -v fatjet_3_msoftdrop 